### ISSUE TITLE
QrCodeImgControl

### ISSUE THREAD

**Issue by Yothri** [Alxandr/QrCode.Net#2]
Hello,

i cant find any examples in the internet for the new(?) QrCodeImgControl for WPF.
I just found a project solution where it was possible to bind a String to the Text Property but this obviiously doesnt work anymore because it needs a DependencyProperty or sth.
Could you give an example?

**Comment by Alxandr** [comment]
Sorry, but this project is just a fork. The original can be found at https://qrcodenet.codeplex.com/. I did not write this code.
