### ISSUE TITLE
Drawing QR Code to a PictureBox with fixed size

### ISSUE THREAD

**Issue by lordofscripts** [Alxandr/QrCode.Net#3]
I am writing a WinForms application in which I have a PictureBox control of a fixed size (68x68) and I would like to use the QrCode.net library to generate a QR Code that fits that 68x68 picture box control. The source string is about 50 characters long.

I tried to use RunSample2 but it draws a big QR. I played with the parameters and more or less got it better with ErrorLevel.M and ModuleSize 2. Is there a better way to do it?

**Comment by Alxandr** [comment]
Sorry, but this is a fork (the original library was not on git/github). And it's been so long I don't remember much about this library (I didn't write it after all). See https://qrcodenet.codeplex.com/
